# Generated by Django 2.0.2 on 2018-04-28 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegUlang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nisn', models.CharField(max_length=8)),
                ('kartu_keluarga', models.CharField(max_length=16)),
                ('nik', models.CharField(max_length=16)),
                ('hobi', models.CharField(max_length=100)),
                ('cita_cita', models.CharField(max_length=100)),
                ('prestasi', models.CharField(max_length=200)),
                ('nilai_skhun', models.DecimalField(decimal_places=2, max_digits=4)),
                ('daftar_ulang', models.BooleanField(default=False)),
                ('nomor_pendaftaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pendaftaran.Pendaftar')),
            ],
        ),
    ]
