# Generated by Django 2.0.2 on 2018-04-07 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrasiulang',
            name='nama',
        ),
        migrations.DeleteModel(
            name='UserPassword',
        ),
        migrations.DeleteModel(
            name='RegistrasiUlang',
        ),
    ]
