# Generated by Django 2.0.2 on 2018-04-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0002_auto_20180407_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftar',
            name='nomor_pendaftaran',
            field=models.IntegerField(null=True),
        ),
    ]
