# Generated by Django 2.0.2 on 2018-05-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0002_regulang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftar',
            name='nomor_pendaftaran',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
