# Generated by Django 2.0.2 on 2018-04-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0003_auto_20180409_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftar',
            name='rerata_indo',
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='pendaftar',
            name='rerata_ipa',
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='pendaftar',
            name='rerata_mapel',
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='pendaftar',
            name='rerata_mtk',
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True),
        ),
    ]
