# Generated by Django 2.0.2 on 2018-05-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0003_auto_20180501_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftar',
            name='nomor_pendaftaran',
            field=models.IntegerField(null=True),
        ),
    ]
