# Generated by Django 2.0.2 on 2018-04-12 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0005_auto_20180411_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrasiUlang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nisn', models.CharField(max_length=8)),
                ('kartu_keluarga', models.CharField(max_length=16)),
                ('nik', models.CharField(max_length=16)),
                ('hobi', models.CharField(max_length=30)),
                ('cita_cita', models.CharField(max_length=50)),
                ('prestasi', models.CharField(max_length=50)),
                ('nilai_skhun', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='pendaftar',
            name='rerata_indo',
        ),
        migrations.RemoveField(
            model_name='pendaftar',
            name='rerata_ipa',
        ),
        migrations.RemoveField(
            model_name='pendaftar',
            name='rerata_mapel',
        ),
        migrations.RemoveField(
            model_name='pendaftar',
            name='rerata_mtk',
        ),
        migrations.AddField(
            model_name='registrasiulang',
            name='nama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pendaftaran.Pendaftar'),
        ),
    ]
