# Generated by Django 2.0.2 on 2018-04-13 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0006_auto_20180413_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrasiulang',
            name='nama',
        ),
        migrations.DeleteModel(
            name='RegistrasiUlang',
        ),
    ]
