# Generated by Django 2.0.2 on 2018-04-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0007_auto_20180413_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftar',
            name='jenis_sekolah',
            field=models.CharField(choices=[('SD', 'SD'), ('MI', 'MI')], default='SD', max_length=2),
        ),
        migrations.AlterField(
            model_name='pendaftar',
            name='agama_anak',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katholik', 'Katholik'), ('Hindu', 'Hindhu'), ('Budha', 'Budha'), ('-', '-')], default='Islam', max_length=10),
        ),
        migrations.AlterField(
            model_name='pendaftar',
            name='agama_ayah',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katholik', 'Katholik'), ('Hindu', 'Hindhu'), ('Budha', 'Budha'), ('-', '-')], default='Islam', max_length=10),
        ),
        migrations.AlterField(
            model_name='pendaftar',
            name='agama_ibu',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katholik', 'Katholik'), ('Hindu', 'Hindhu'), ('Budha', 'Budha'), ('-', '-')], default='Islam', max_length=10),
        ),
        migrations.AlterField(
            model_name='pendaftar',
            name='jenis_kelamin',
            field=models.CharField(choices=[('Laki-laki', 'L'), ('Perempuan', 'P')], default='Laki-laki', max_length=10),
        ),
    ]
